#
# Copyright (c) 2024, Oracle and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.  Oracle designates this
# particular file as subject to the "Classpath" exception as provided
# by Oracle in the LICENSE file that accompanied this code.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.
#

name: 'Test OpenJDK pull requests on LibGraal'

on:
  # Runs every 1 hour at 11 mins past the hour
  schedule:
    - cron: '11 * * * *'
  workflow_dispatch:

# Only run one instance of this workflow per branch at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
    
jobs:
  test-pull-requests:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Test LibGraal
      env:
        GH_TOKEN: ${{ github.token }}
        SLACK_AUTH_TOKEN: ${{ secrets.SLACK_AUTH_TOKEN }}
      run: python -u .github/scripts/test-openjdk-pullrequests.py

    - name: Failure Logs
      run: |
        if [ -f failure_logs ]; then
          for name in $(<failure_logs); do
            echo "::group::${name} (last 100 lines)"
            tail -100 ${name}
            echo "::endgroup::"
          done
        else
          echo "No failure logs to dump."
        fi
      if: always()

    - name: 'Upload build and test results'
      uses: actions/upload-artifact@v4
      with:
        path: results/
        name: logs
      if: always()
